baseurl             = "https://reubenharry.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-GB"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "zen"
author              = "Reuben Cohn-Gordon"
title               = "Reuben Cohn-Gordon"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

#[[menu.main]]
#name                   = "About"
#weight                 = -110
#identifier             = "about"
#url                    = "/about/"

# [[menu.main]]
# name                   = "Code"
# weight                 = -100
# identifier             = "code"
# url                    = "/code/"


[params]
  cacheBustCSS	=	 true        # Add a cache busting hash on styles.css
  cacheBustJS	=	 true         # Add a cache busting hash on script.js
  contact	=	 "info@example.org"
  copyright	=	 ""
  dateformat	=	 ""            # Set the date format, default to "2 January, 2006"
  description	=	 "hello"           # Set site description, used in meta tags and JSON-LD
  favicon	=	 ""               # Relative path to favicon in json feed, no leading slash.
  feedlinks	=	 true           # Show feed links in the footer.
  footer	=	 "A [example.org](https://example.org/) production."
  icon		=	 ""                  # Relative path to icon in json feed, no leading slash.
  image		=	 ""                 # Relative path to site image in JSON-LD, no leading slash.
  imageMaxWidth	=	 ""         # Max width for images added via figure shortcode.
  jquery	=	 true              # Add jQuery
  languageDir	=	 ""           # Set ltr or rtl, defaults to ltr.
  logo		=	 false               # Turn off the logo.
  microUsername	=	 ""         # Your micro.blog username.
  mobileMenu	=	 true          # Turn on a mobile menu on small screens.
  poweredby	=	 true           # Show powered by hugo in footer
  search	=	 true              # Site search with DuckDuckGo.
  searchSize	=	 20            # Search field size, default 20.
  sidebar	=	 true             # Show a sidebar to the right
  submitted	=	 true           # Show author and date information for a post.
