---
title: "Reuben Cohn-Gordon"
baseURL: "https://reubenharry.github.io"
theme: "zen"
languageCode: "en-GB"
defaultContentLanguage: "en"
metaDataFormat: "yaml"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
summaryLength: 1
rssLimit: 20
author:
  name: "Reuben Cohn-Gordon"
  url: "https://reubenharry.github.io"
  avatar: "static/img/profile.png"

outputs:
  home: ["HTML","RSS", "JSON"]
  section: ["HTML","RSS", "JSON"]

params:
  cacheBustCSS: false
  cacheBustJS: false
  contact: "reubenharry@gmail.com"
  description: ""
  dateformat: "2 January, 2006"
  favicon: "icon-64.png"
  feedlinks: true
  icon: "apple-touch-icon-180.png"
  image: "xdeb-org.jpg"
  imageMaxWidth: 400
  jquery: true
  languageDir: "ltr"
  logo: false
  mobileMenu: true
  poweredby: false
  search: false
  searchSize: 0
  sidebar: true
  submitted: true

permalinks:
  blog: "blog/:slug/"

staticDir:
  - static
